version: '3.7'

services:
  postgres:
    image: postgres:15.1-alpine
    env_file:
      - .env
    networks:
      - postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: app
    depends_on:
      - postgres
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - postgres
    volumes:
      - /etc/letsencrypt/live/ownchgk.ru/fullchain.pem:/etc/letsencrypt/live/ownchgk.ru/fullchain.pem
      - /etc/letsencrypt/live/ownchgk.ru/privkey.pem:/etc/letsencrypt/live/ownchgk.ru/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
    ports:
      - "80:80"
      - "443:443"

networks:
  postgres:
    driver: bridge
