export const AUTHORIZE_USER_WITH_ROLE = 'AUTHORIZE_USER_WITH_ROLE';
export const LOG_OUT = 'LOG_OUT';
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const ADD_USER_TEAM = 'ADD_USER_TEAM';
export const ADD_USER_NAME = 'ADD_USER_NAME';